fname = input ("Enter First name: ")
lname = input ("Enter Last name: ")
mname = input ("Enter Middle name: ")
bday = input ("Enter Birthday: ")
gender = input ("Enter Gender: ")
address = input ("Enter Address: ")
course = input ("Enter Course: ")
yearlvl = input ("Enter Year level: ")
print ("My name is:", fname + " " + mname + " " + lname)
print ("I am", gender)
print ("I was born in", bday)
print ("I live in", address)
print ("I am", course + " " + yearlvl)
